language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install -g bower
- npm install
- bower install
script: echo "Deploying!"
before_deploy: npm run build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: develop
  project: hoverboard-dev
  token:
    secure: p3CjZF4r8zlsx700kHg65kvmTarueRUn9wK5mm5dcUbCyLYnm3F81z0yfB7u5NFWOOUNsY2wWp6wwS2iM6ifzf/vPw2OpqxW0or0wXrIFJ+eL5+b3uvmgNOFw8pOf9UxaSCcZzwv7rotmQ2fcpZoxSyWR5p6VO/cwnGWjS+2eE42VlfRE6pqJqErmba/Ni4mg3QeQtjXKUcGBUOZmMIIRQaVEjrNKdOjOTxp5QU0kUbkRLpEjKe/40E8rUR7EzJKgBDuyt88XXJEnglWzFVaIjvDsSFsfJHCTrCbaIT5OAZZ7CN90L+EiTIaBcnANOiuYTYMaH8dcy8BzWjTsaxFP59gXr5EEuCeTcLknjISaLoqzZ8zi6uZx8y9H0crDpsKnSFPL8Wj3n4S6pbZMHlJrZPmfN3rJk4AVoeJuMX/c/B3aK++umf5VIUMAhySuUCrMZYbxGPaOorbODzNUTp2mXMifZac7LHWbU4NeSC2NFqe+bk34WXu1I2+fcruSm4Vj6d4AllhwV292lEpouwwtRUXikUadcjfhlKF4asIR9a5D5x3fit4vukpk6YJquIHOG5cGfosHVXCkZlwLAbtp/7Xulosuc/Ev9uZ80aHEN0DM+BNi+CCZS26v78f4kqKxlke4YnFBPmkyj9zVLtHI6NVS3UTUr5660Z/j9lV4AI=
